/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sinemaproje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Doğan
 */
public class KoltukSec extends javax.swing.JFrame {

    /**
     * Creates new form KoltukSec
     */
    public KoltukSec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        c = new javax.swing.JToggleButton();
        b = new javax.swing.JToggleButton();
        d = new javax.swing.JToggleButton();
        j = new javax.swing.JToggleButton();
        f = new javax.swing.JToggleButton();
        e = new javax.swing.JToggleButton();
        g = new javax.swing.JToggleButton();
        m = new javax.swing.JToggleButton();
        h = new javax.swing.JToggleButton();
        k = new javax.swing.JToggleButton();
        l = new javax.swing.JToggleButton();
        v = new javax.swing.JToggleButton();
        y = new javax.swing.JToggleButton();
        u = new javax.swing.JToggleButton();
        o = new javax.swing.JToggleButton();
        n = new javax.swing.JToggleButton();
        z = new javax.swing.JToggleButton();
        ee = new javax.swing.JToggleButton();
        aa = new javax.swing.JToggleButton();
        bb = new javax.swing.JToggleButton();
        cc = new javax.swing.JToggleButton();
        x = new javax.swing.JToggleButton();
        dd = new javax.swing.JToggleButton();
        a = new javax.swing.JToggleButton();
        ff = new javax.swing.JToggleButton();
        gg = new javax.swing.JToggleButton();
        ll = new javax.swing.JToggleButton();
        mm = new javax.swing.JToggleButton();
        nn = new javax.swing.JToggleButton();
        xx = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("                          PERDE");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        c.setText("C");
        c.setMaximumSize(new java.awt.Dimension(66, 66));
        c.setMinimumSize(new java.awt.Dimension(66, 66));
        c.setPreferredSize(new java.awt.Dimension(66, 66));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        b.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b.setText("B");
        b.setMaximumSize(new java.awt.Dimension(66, 66));
        b.setMinimumSize(new java.awt.Dimension(66, 66));
        b.setPreferredSize(new java.awt.Dimension(66, 66));
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        d.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        d.setText("D");
        d.setMaximumSize(new java.awt.Dimension(66, 66));
        d.setMinimumSize(new java.awt.Dimension(66, 66));
        d.setPreferredSize(new java.awt.Dimension(66, 66));
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        j.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        j.setText("J");
        j.setMaximumSize(new java.awt.Dimension(66, 66));
        j.setMinimumSize(new java.awt.Dimension(66, 66));
        j.setPreferredSize(new java.awt.Dimension(66, 66));
        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });

        f.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        f.setText("F");
        f.setMaximumSize(new java.awt.Dimension(66, 66));
        f.setMinimumSize(new java.awt.Dimension(66, 66));
        f.setPreferredSize(new java.awt.Dimension(66, 66));
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        e.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        e.setText("E");
        e.setMaximumSize(new java.awt.Dimension(66, 66));
        e.setMinimumSize(new java.awt.Dimension(66, 66));
        e.setPreferredSize(new java.awt.Dimension(66, 66));
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        g.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        g.setText("G");
        g.setMaximumSize(new java.awt.Dimension(66, 66));
        g.setMinimumSize(new java.awt.Dimension(66, 66));
        g.setPreferredSize(new java.awt.Dimension(66, 66));
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });

        m.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        m.setText("M");
        m.setMaximumSize(new java.awt.Dimension(66, 66));
        m.setMinimumSize(new java.awt.Dimension(66, 66));
        m.setPreferredSize(new java.awt.Dimension(66, 66));
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        h.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        h.setText("H");
        h.setMaximumSize(new java.awt.Dimension(66, 66));
        h.setMinimumSize(new java.awt.Dimension(66, 66));
        h.setPreferredSize(new java.awt.Dimension(66, 66));
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });

        k.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        k.setText("K");
        k.setMaximumSize(new java.awt.Dimension(66, 66));
        k.setMinimumSize(new java.awt.Dimension(66, 66));
        k.setPreferredSize(new java.awt.Dimension(66, 66));
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });

        l.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        l.setText("L");
        l.setMaximumSize(new java.awt.Dimension(66, 66));
        l.setMinimumSize(new java.awt.Dimension(66, 66));
        l.setPreferredSize(new java.awt.Dimension(66, 66));
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });

        v.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        v.setText("V");
        v.setMaximumSize(new java.awt.Dimension(66, 66));
        v.setMinimumSize(new java.awt.Dimension(66, 66));
        v.setPreferredSize(new java.awt.Dimension(66, 66));
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        y.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        y.setText("Y");
        y.setMaximumSize(new java.awt.Dimension(66, 66));
        y.setMinimumSize(new java.awt.Dimension(66, 66));
        y.setPreferredSize(new java.awt.Dimension(66, 66));
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });

        u.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        u.setText("U");
        u.setMaximumSize(new java.awt.Dimension(66, 66));
        u.setMinimumSize(new java.awt.Dimension(66, 66));
        u.setPreferredSize(new java.awt.Dimension(66, 66));
        u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uActionPerformed(evt);
            }
        });

        o.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        o.setText("O");
        o.setMaximumSize(new java.awt.Dimension(66, 66));
        o.setMinimumSize(new java.awt.Dimension(66, 66));
        o.setPreferredSize(new java.awt.Dimension(66, 66));
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });

        n.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        n.setText("N");
        n.setMaximumSize(new java.awt.Dimension(66, 66));
        n.setMinimumSize(new java.awt.Dimension(66, 66));
        n.setPreferredSize(new java.awt.Dimension(66, 66));
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        z.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        z.setText("Z");
        z.setMaximumSize(new java.awt.Dimension(66, 66));
        z.setMinimumSize(new java.awt.Dimension(66, 66));
        z.setPreferredSize(new java.awt.Dimension(66, 66));
        z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zActionPerformed(evt);
            }
        });

        ee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ee.setText("EE");
        ee.setMaximumSize(new java.awt.Dimension(66, 66));
        ee.setMinimumSize(new java.awt.Dimension(66, 66));
        ee.setPreferredSize(new java.awt.Dimension(66, 66));
        ee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeActionPerformed(evt);
            }
        });

        aa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aa.setText("AA");
        aa.setMaximumSize(new java.awt.Dimension(66, 66));
        aa.setMinimumSize(new java.awt.Dimension(66, 66));
        aa.setPreferredSize(new java.awt.Dimension(66, 66));
        aa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaActionPerformed(evt);
            }
        });

        bb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bb.setText("BB");
        bb.setMaximumSize(new java.awt.Dimension(66, 66));
        bb.setMinimumSize(new java.awt.Dimension(66, 66));
        bb.setPreferredSize(new java.awt.Dimension(66, 66));
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });

        cc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cc.setText("CC");
        cc.setMaximumSize(new java.awt.Dimension(66, 66));
        cc.setMinimumSize(new java.awt.Dimension(66, 66));
        cc.setPreferredSize(new java.awt.Dimension(66, 66));
        cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccActionPerformed(evt);
            }
        });

        x.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        x.setText("X");
        x.setMaximumSize(new java.awt.Dimension(66, 66));
        x.setMinimumSize(new java.awt.Dimension(66, 66));
        x.setPreferredSize(new java.awt.Dimension(66, 66));
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        dd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dd.setText("DD");
        dd.setMaximumSize(new java.awt.Dimension(66, 66));
        dd.setMinimumSize(new java.awt.Dimension(66, 66));
        dd.setPreferredSize(new java.awt.Dimension(66, 66));
        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });

        a.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        a.setText("A");
        a.setMaximumSize(new java.awt.Dimension(66, 66));
        a.setMinimumSize(new java.awt.Dimension(66, 66));
        a.setPreferredSize(new java.awt.Dimension(66, 66));
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        ff.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ff.setText("FF");
        ff.setMaximumSize(new java.awt.Dimension(66, 66));
        ff.setMinimumSize(new java.awt.Dimension(66, 66));
        ff.setPreferredSize(new java.awt.Dimension(66, 66));
        ff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffActionPerformed(evt);
            }
        });

        gg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gg.setText("GG");
        gg.setMaximumSize(new java.awt.Dimension(66, 66));
        gg.setMinimumSize(new java.awt.Dimension(66, 66));
        gg.setPreferredSize(new java.awt.Dimension(66, 66));
        gg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ggActionPerformed(evt);
            }
        });

        ll.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ll.setText("LL");
        ll.setMaximumSize(new java.awt.Dimension(66, 66));
        ll.setMinimumSize(new java.awt.Dimension(66, 66));
        ll.setPreferredSize(new java.awt.Dimension(66, 66));
        ll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llActionPerformed(evt);
            }
        });

        mm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mm.setText("MM");
        mm.setMaximumSize(new java.awt.Dimension(66, 66));
        mm.setMinimumSize(new java.awt.Dimension(66, 66));
        mm.setPreferredSize(new java.awt.Dimension(66, 66));
        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });

        nn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nn.setText("NN");
        nn.setMaximumSize(new java.awt.Dimension(66, 66));
        nn.setMinimumSize(new java.awt.Dimension(66, 66));
        nn.setPreferredSize(new java.awt.Dimension(66, 66));
        nn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nnActionPerformed(evt);
            }
        });

        xx.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        xx.setText("XX");
        xx.setMaximumSize(new java.awt.Dimension(66, 66));
        xx.setMinimumSize(new java.awt.Dimension(66, 66));
        xx.setPreferredSize(new java.awt.Dimension(66, 66));
        xx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(xx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Film name:");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Date/Hour:");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Apply and buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText(" Back to previous page");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText(" Sign out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Koltuk:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kullanıcı adı:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("satın alma geçmişi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Cancellation");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addGap(34, 34, 34)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
         try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='C' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("C");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
        
    }//GEN-LAST:event_cActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='B' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("B");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_bActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='D' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("D");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_dActionPerformed

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='J' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("J");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_jActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
       try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='F' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("F");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_fActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='E' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("E");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_eActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='G' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("G");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_gActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='M' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("M");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_mActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='H' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("H");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_hActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='K' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("K");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_kActionPerformed

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='L' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("L");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_lActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='V' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("V");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_vActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='Y' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("Y");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_yActionPerformed

    private void uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='U' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("U");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_uActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='O' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("O");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_oActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='N' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("N");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_nActionPerformed

    private void zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='Z' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("Z");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_zActionPerformed

    private void eeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='EE' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("EE");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_eeActionPerformed

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='AA' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("AA");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_aaActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='BB' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("BB");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_bbActionPerformed

    private void ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='CC' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("CC");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_ccActionPerformed

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='X' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("X");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_xActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='DD' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("DD");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_ddActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
         try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='A' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("A");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
        
       
    }//GEN-LAST:event_aActionPerformed

    private void ffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='FF' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("FF");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_ffActionPerformed

    private void ggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ggActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='GG' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("GG");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_ggActionPerformed

    private void llActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='LL' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("LL");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_llActionPerformed

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='MM' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("MM");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_mmActionPerformed

    private void nnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nnActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='NN' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("NN");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_nnActionPerformed

    private void xxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xxActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String query = "select Koltuk_adi from bilet_veri where Koltuk_adi='XX' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            
            ResultSet rs = stmt.executeQuery(query);
            
            
            if (rs.next()) {
              jLabel4.setText("Koltuk dolu");
           }
            else{
                jLabel4.setText("XX");
            }
           
            
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_xxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Film_adi= jLabel2.getText();
        String Tarih_Saat = jLabel3.getText();
        String Koltuk_adi = jLabel4.getText();
        String Alan_kisi = jTextField1.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = (Statement) con.createStatement();
            st.executeUpdate("insert into bilet_veri values('" + Film_adi + "','" + Tarih_Saat + "','" + Koltuk_adi + "','" + Alan_kisi + "')");
            JOptionPane.showMessageDialog(null, "işlem basarili");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "hatalı");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        ekran Ekran = new ekran();
        Ekran.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String K_ad=jTextField1.getText();
            String query = "select * from bilet_veri where Alan_kisi= '"+K_ad+"'";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String Film_adi = rs.getString("Film_adi");
                String Tarih_Saat = rs.getString("Tarih_Saat");
                String Koltuk_adi = rs.getString("Koltuk_adi");
                String Alan_kisi = rs.getString("Alan_kisi");

                jTextArea1.setText(Film_adi+" "+" "+Tarih_Saat+" "+Alan_kisi+" "+Koltuk_adi);
                
            }
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "E" + Ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/netbeans_verileri", "root", "Dogan.04");
            Statement stmt = con.createStatement();
            String veril = jLabel2.getText();
            String K_ad=jTextField1.getText();
            String query = "delete FROM bilet_veri WHERE Alan_kisi='"+K_ad+"' AND Film_adi = '"+veril+"'";
            String Koltuk_adi;
            PreparedStatement prest = con.prepareStatement(query);
            prest.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "İşlem başaraılı");
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Error...  " + Ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        JOptionPane.showMessageDialog(null, "Çıkış yapıldı");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KoltukSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KoltukSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KoltukSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KoltukSec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KoltukSec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton a;
    private javax.swing.JToggleButton aa;
    private javax.swing.JToggleButton b;
    private javax.swing.JToggleButton bb;
    private javax.swing.JToggleButton c;
    private javax.swing.JToggleButton cc;
    private javax.swing.JToggleButton d;
    private javax.swing.JToggleButton dd;
    private javax.swing.JToggleButton e;
    private javax.swing.JToggleButton ee;
    private javax.swing.JToggleButton f;
    private javax.swing.JToggleButton ff;
    private javax.swing.JToggleButton g;
    private javax.swing.JToggleButton gg;
    private javax.swing.JToggleButton h;
    private javax.swing.JToggleButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton k;
    private javax.swing.JToggleButton l;
    private javax.swing.JToggleButton ll;
    private javax.swing.JToggleButton m;
    private javax.swing.JToggleButton mm;
    private javax.swing.JToggleButton n;
    private javax.swing.JToggleButton nn;
    private javax.swing.JToggleButton o;
    private javax.swing.JToggleButton u;
    private javax.swing.JToggleButton v;
    private javax.swing.JToggleButton x;
    private javax.swing.JToggleButton xx;
    private javax.swing.JToggleButton y;
    private javax.swing.JToggleButton z;
    // End of variables declaration//GEN-END:variables
}
